### ISSUE TITLE
Relicense to AGPLv3

### ISSUE THREAD

**Issue by Vauff** [Vauff/Maunz-Discord#97]
I plan to relicense Maunz to the [GNU Affero General Public License v3](https://www.gnu.org/licenses/agpl-3.0.en.html). This will (maybe) require the permission of all code contributors.

- [x] @bl4ckscor3
- [x] @raqbit
- [x] @Trevor159
- [x] @PolarizedIons

**Comment by bl4ckscor3** [comment]
Performing this change sounds reasonable, it's good from my side.

**Comment by PolarizedIons** [comment]
:+1: sounds good

**Comment by Vauff** [comment]
The [GPL FAQ on license compatibility](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) seems to confirm my belief that this is already permitted without contributor approval, so I will be going forward with the change. However I would still like this completed just in case.

**Comment by Trevor159** [comment]
👍
